image_width: 640
image_height: 480
camera_name: camera_color
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
camera_matrix:
  rows: 3
  cols: 3
  data:
    - 604.846740722656
    - 0.0
    - 334.881103515625
    - 0.0
    - 604.4609375
    - 256.258666992188
    - 0.0
    - 0.0
    - 1.0
rectification_matrix:
  rows: 3
  cols: 3
  data:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    - 1.0
projection_matrix:
  rows: 3
  cols: 4
  data:
    - 604.846740722656
    - 0.0
    - 334.881103515625
    - 0.0
    - 0.0
    - 604.4609375
    - 256.258666992188
    - 0.0
    - 0.0
    - 0.0
    - 1.0
    - 0.0
