<?xml version="1.0"?>
<package format="3">
  <name>gst_realsense_launch</name>
  <version>0.1.0</version>
  <description>A ROS 2 package for high-performance Intel RealSense camera streaming using GStreamer. It supports multiple camera streams with hardware-accelerated encoding, network transmission, and direct integration with ROS 2 topics.</description>
  <maintainer email="chuntsehsu@gmail.com">cthsu</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>gscam</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>depth_image_proc</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
